nf-core/ampliseq

- CHANGELOG.md
- assets/multiqc_config.yaml
- conf/base.config
- environment.yml
- main.nf
MultiQC does not work with the MatPlotLib version 3.1.0 that is required by QIIME2. MultiQC uses MatPlotLib for static images but not when creating interactive charts, therefore, the creation of static images is now prevented.
Also, errors by MultiQC are no longer ignored.
> Fix MultiQC

- CHANGELOG.md
- bin/dada2_chimrem.r
Fixed sorting in dada2_chimrem.r. This resolves issue #187.
> Fix bug when sorting sample ids for feature-table.tsv (PacBio data)

- CHANGELOG.md
- Dockerfile
- main.nf
Changed the if-statments in the trimming process so that if `--double_primer` is set and `--retain_untrimmed` is not set, cutadapt will be run twice on the input data. This resolves #197. I've tested the changes with `test_doubleprimers`, `test` and `test_multi` (the two latter by specifying `--double_primer`).
> Fixed so that cutadapt actually runs twice when --double_primer is specified

- .gitignore
- bin/taxref_reformat_gtdb.sh
- bin/taxref_reformat_unite.sh
I've updated the Unite and GTDB reformatting scripts so they remove species information. I kept the general one for you @emnilsson, since you know that better.
> Remove species from assignTaxonomy fasta files (Unite & GTDB)

- conf/modules.config
- modules/local/dada2_denoising.nf
While working on a special request (somebody had a bad experimental design, the amplicon was longer than anticipated and therefore read pairs were overlapping only 9 bp instead of DADA2's minimum standard setting of 12bp), I found that the standard settings in `modules.config` for `mergePairs` is wrong. This actually did not impact normal use cases but does impact those edge cases when supplying a custom `modules.config` with modified `minOverlap` for `mergePairs` as I did (in short: it did not work). Here I correct that values.
> Correcting faulty default settings

- conf/modules.config
- conf/ref_databases.config
- modules/local/dada2_addspecies.nf
- modules/local/dada2_merge.nf
- modules/local/dada2_taxonomy.nf
I made a couple of updates that are somehow related:
1. Made sure ASV_ID is a header and not a "rowname" (issue #263)
2. Updated the GTDB links to the official site since the alternative was down. (@emnilsson never got these to download, but I don't have any problems.)
3. Added `confidence` to `ASV_tax.tsv` and `ASV_tax_species.tsv` (issue #243). (I chose to use the name `confidence` because that's what it was called in the 1.n series, i.e. QIIME2-based, even though bootstrap is more explanatory.)
> DADA2 confidence

- conf/modules.config
- workflows/ampliseq.nf
This solves the issue with DADA2 quality profiling sometimes failing. It happened on reads with a length of 0.
> Set minimum length of cutadapt output reads to 1

- .github/workflows/ci.yml
- CHANGELOG.md
- CITATIONS.md
- README.md
- conf/test.config
- conf/test_doubleprimers.config
- conf/test_full.config
- conf/test_multi.config
- conf/test_pacbio_its.config
- docs/output.md
- nextflow.config
- workflows/ampliseq.nf
Some small changes:
- remove params.outdir from test profiles, because `tracedir` was still default and therefore test runs had two results folders.
- min nxf from 20.10.0 to 21.04.0, because downloading multiple containers with singularity and nxf 20.10.0 failed
- adjust README badges, purely cosmetic
- add CITATIONS.md, purely cosmetic
- add warning/reminder for trunclenf/r, this (1) gives a warning when one or both values that are automatically chosen are aparently too small (<=10) and (2) a reminder what values were automatically chosen and how to modify those.
> Cosmetic and low impact changes

- CHANGELOG.md
- bin/taxref_reformat_qiime_greengenes85.sh
- bin/taxref_reformat_qiime_silva138.sh
- bin/taxref_reformat_qiime_unite.sh
- conf/ref_databases.config
- conf/test.config
- conf/test_full.config
- modules/local/format_taxonomy_qiime.nf
- nextflow.config
- nextflow_schema.json
- subworkflows/local/qiime2_preptax.nf
- workflows/ampliseq.nf
This is supposed to solve #261 
I added a parameter `--qiime_ref_taxonomy` alongside `--dada_ref_taxonomy` which works essentially identical.
Currently, I added `silva`, `unite-fungi`, `unite-alleuk`, and for quick runs `greengenes85`. Default is not using QIIME2 classification. Test profile includes `greengenes85`.
> add --qiime_ref_taxonomy

- bin/taxref_reformat_gtdb.sh
- bin/taxref_reformat_pr2.sh
- bin/taxref_reformat_unite.sh
- bin/taxref_standard.sh
- conf/modules.config
- conf/ref_databases.config
- modules/local/dada2_addspecies.nf
- modules/local/dada2_taxonomy.nf
- modules/local/qiime2_ancom_tax.nf
- subworkflows/local/qiime2_ancom.nf
* Added a PR2 formatting script
* Made sure all formatting scripts outputs domain, kingdom etc. ranks
* Made sure Ancom processes isn't run when input table contains a single row/taxon
(A number of edited lines in the diffs are only changed to have four spaces instead of a tab to start the line. Maybe this should be made more consistently?)
> PR2 and Ancom fix

- CHANGELOG.md
- README.md
- conf/modules.config
- conf/test.config
- docs/output.md
- nextflow.config
- nextflow_schema.json
- workflows/ampliseq.nf
> add --cut_dada_ref_taxonomy

- conf/ref_databases.config
- nextflow_schema.json
I attempted to improve documentation about reference taxonomy.
I added among other that text:
> - GTDB - Genome Taxonomy Database - 16S rRNA
> - PR2 - Protist Reference Ribosomal Database - 18S rRNA
> - RDP - Ribosomal Database Project  - 16S rRNA
> - SILVA ribosomal RNA gene database project  - 16S rRNA
> - UNITE - eukaryotic nuclear ribosomal ITS region  - ITS
Please check if those categories (16S/18S/ITS) are fine.
By the way, UNITE has already newer versions. But I think its more important to have that pipeline version released than adding more reference taxonomy database versions.
> Improve ref taxonomy documentation

- CHANGELOG.md
- nextflow.config
- nextflow_schema.json
- workflows/ampliseq.nf
> `--max_len` now accepts integers as expected

- CHANGELOG.md
- CITATIONS.md
- conf/modules.config
- conf/test_doubleprimers.config
- conf/test_full.config
- docs/output.md
- modules/local/picrust.nf
- nextflow.config
- nextflow_schema.json
- subworkflows/local/qiime2_export.nf
- workflows/ampliseq.nf
> Add Picrust2

- CHANGELOG.md
- bin/combine_table.r
- docs/output.md
- modules/local/combine_table.nf
- subworkflows/local/qiime2_export.nf
- workflows/ampliseq.nf
I prefer to have two relative abundance tables with taxonomic classifications and sequences, for DADA2 and QIIME2 classifications. Those tables are actually the info that my customers prefer and expect but those are currently only produced for QIIME2 classifications. It is quite tedious to merge those tables manually to satisfy the expectations, so here is the automation.
> Export two ASV relative abundance tables with DADA2 or QIIME2 classification

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/WorkflowAmpliseq.groovy
- subworkflows/local/parse_input.nf
- workflows/ampliseq.nf
Fixed fasta input and activated `test_fasta` that was added in #314 .
> fix fasta input

- CHANGELOG.md
- conf/test_doubleprimers.config
- subworkflows/local/parse_input.nf
- workflows/ampliseq.nf
This is to solve:
- #330 --skip_fastqc is not usable
- #329 Error message can be misleading when no raw data is found
> Fix --skip_fastqc and error message when no input data is found

- CHANGELOG.md
- conf/test_multi.config
- lib/WorkflowAmpliseq.groovy
- nextflow.config
- nextflow_schema.json
- workflows/ampliseq.nf
DADA2's taxonomic classification on species level with `addSpecies` can be peak memory (RAM) requirement for the pipeline. Here the `--skip_dada_addspecies` is added to be able to skip that step when memory (RAM) is limiting.
However,  `--skip_dada_addspecies` is incompatible with `--cut_its` and `--sbdiexport` because those expect species level annotation currently.
> Add --skip_dada_addspecies

- CHANGELOG.md
- nextflow.config
- nextflow_schema.json
- subworkflows/local/cutadapt_workflow.nf
- subworkflows/local/parse_input.nf
Closes https://github.com/nf-core/ampliseq/issues/340
Sample with input files and files after cutadapt with low read numbers (gz'ed file size < 1Kb) are removed. Either with error that stops the pipeline or it continues when using `--ignore_empty_input_files` or `--ignore_failed_trimming`. Either way, an error message with sample names will highlight what samples were failing.
I did not add a check after DADA2's quality filter filtntrim, because the error message there is actually quite clear.
> filter empty files

- CHANGELOG.md
- bin/add_full_sequence_to_taxfile.py
- lib/WorkflowAmpliseq.groovy
- modules/local/format_taxresults.nf
- nextflow_schema.json
- workflows/ampliseq.nf
This adresses issue #370
Option --skip_dada_addspecies was not compatible with --cut_its, but now this should be fixed.
> Make addSpecies optional also when using cut_its

- CHANGELOG.md
- workflows/ampliseq.nf
This closes https://github.com/nf-core/ampliseq/issues/358
> add cutadapt results to multiqc report

- CHANGELOG.md
- docs/output.md
- lib/WorkflowAmpliseq.groovy
- nextflow_schema.json
Using `--sbdiexport` and `--skip_taxonomy` lead to an error, because sbdiexport expect taxonomy classifications. I have added here a parameter check with a proper error message.
> error message when using --sbdiexport and --skip_taxonomy

- CHANGELOG.md
- CITATIONS.md
- README.md
This is to add links to the bytesize slides/video and to correct typo's.
> add bytesize talk info

- CHANGELOG.md
- subworkflows/local/cutadapt_workflow.nf
- subworkflows/local/parse_input.nf
Closes https://github.com/nf-core/ampliseq/issues/399
I have rephrased the messages when encountering empty input files or empty files after trimming with cutadapt. Depending on the parameters given its either an error message or when ignoring the empty files, a warning message only.
> Rephrase warn/error messages with empty files

- CHANGELOG.md
- conf/modules.config
- docs/output.md
- nextflow_schema.json
- workflows/ampliseq.nf
The option "its1" is added to --cut_its, in addition to "its2" and "full" that were added in #390
> Add its1 option to cut_its

- CHANGELOG.md
- modules/local/dada2_merge.nf
Fixes https://github.com/nf-core/ampliseq/issues/423
> fix dashes in sampleID

- CHANGELOG.md
- conf/modules.config
The number of records to sample from a fastq file is herein decreased from `5e+06` to `5e+04` for plotQualityProfile (DADA2_QUALITY), therefore a smaller subset of reads is sampled for determining `--trunlenf` and `--trunclenr`. This should make the process more robust also from larger data sets.
This was also mentioned in https://github.com/nf-core/ampliseq/issues/422
> change plotQualityProfile settings

- CHANGELOG.md
- conf/test_multi.config
- lib/WorkflowAmpliseq.groovy
- nextflow.config
- nextflow_schema.json
- workflows/ampliseq.nf
Addresses user feedback that the visualization of read quality parameters can be quite resource consuming and is not always needed. 
Also, it was mentioned in https://github.com/nf-core/ampliseq/issues/422.
> add --skip_dada_quality

- CHANGELOG.md
- conf/modules.config
- modules/local/dada2_err.nf
As described in the CHANGELOG:
> The minimum number of total bases to use for error rate learning by default is 1e8 (DADA2, learnErrors, nbases). Previously, samples were read in the provided order until enough reads were obtained (DADA2, learnErrors, randomize=FALSE). Now, samples are picked at random from those provided (DADA2, learnError, randomize=TRUE) and a seed is set.
This is to allow larger runs (e.g. NovaSeq) to obtain random (but reproducible with a seed) samples instead of ordered input.
> randomize samples for DADA2's learnErrors

- CHANGELOG.md
- modules/local/format_taxonomy.nf
- modules/local/format_taxonomy_qiime.nf
- modules/local/metadata_all.nf
- modules/local/qiime2_diversity_alpha.nf
- modules/local/qiime2_diversity_beta.nf
- modules/local/qiime2_filterasv.nf
- modules/local/rename_raw_data_files.nf
- subworkflows/local/qiime2_ancom.nf
- subworkflows/local/qiime2_diversity.nf
- workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/447
While making sure that `--metadata_category` propagates to all relevant processes correctly (which was before not given), I changed `ch_metacolumn_all` & `ch_metacolumn_pairwise` to contain one value per channel entry instead of one comma separated channel entry. The latter than also means that parallelization is maximized. I touched here code from the very beginning of ampliseq and I hope it did improve overall.
Edit: because the tests fail due to container problems I also fixed https://github.com/nf-core/mag/pull/315 that followed https://github.com/nf-core/rnaseq/issues/764.
> fix --metadata_category

- CHANGELOG.md
- bin/add_sh_to_taxonomy.py
- bin/sbdiexport.R
- bin/sbdiexportreannotate.R
- workflows/ampliseq.nf
Modified SBDI-export scripts to add SH information, if available. 
Input channels to SBDIEXPORT and SBDIEXPORTREANNOTATE are changed from DADA2_ADDSPECIES.out.tsv to ch_dada2_tax to capture the SH information. The tests I've done run as expected, but please let me know if you think this change will break anything.
> Add SH information to sbdi export

- CHANGELOG.md
- lib/WorkflowAmpliseq.groovy
Closes #454. 
An error will occur when only one of `--trunclenf` and `--trunclenr` is set. Before, if only one of those were set, the value would be silently ignored.
> Require trunclenf and trunclenr to be set both or none

- CHANGELOG.md
- docs/output.md
- workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/347.
> Export input and metadata

- CHANGELOG.md
- conf/modules.config
- conf/test_fasta.config
- lib/WorkflowAmpliseq.groovy
- modules/local/dada2_addspecies.nf
- modules/local/dada2_taxonomy.nf
- nextflow.config
- nextflow_schema.json
I attempted to make taxonomic levels for DADA2's assignTaxonomy and addSpecies flexible, i.e. not hardcoded, but adjustable with the parameter `--dada_assign_taxlevels <comma separated string>`.
Currently I see two restrictions:
- DADA2's addSpecies expects a "Genus" level, so that has to be include at least.
- sbdiexport expects the exact previously used taxonomic ranks, so I made that default and raise an error when attempting to use `--sbdiexport` and `--dada_assign_taxlevels`.
This is supposed to aid https://github.com/nf-core/ampliseq/pull/459 and allow later custom db additions as requested in https://github.com/nf-core/ampliseq/issues/427.
> Make dada2 taxlevels flexible

- .github/workflows/ci.yml
- CHANGELOG.md
- conf/test_reftaxcustom.config
- lib/WorkflowAmpliseq.groovy
- nextflow.config
- nextflow_schema.json
- workflows/ampliseq.nf
Added two parameters that allow to supply DADA2's assignTaxonomy and addSpecies directly with files, i.e. custom databases.
Adresses https://github.com/nf-core/ampliseq/issues/427
edit: possibly some more documentation might be good? 
- Maybe in `docs/usage.md` a new section for taxonomy databases and custom databases? Not sure if ever someone looks into those though.
- README.md: `and, currently, taxonomic assignment of 16S, ITS and 18S amplicons.` could be changed to `and taxonomic assignment of 16S, ITS and 18S amplicons, or using custom databases.`?
> Custom dada tax ref db input

- CHANGELOG.md
- bin/taxref_reformat_gtdb.sh
- bin/taxref_reformat_midori2.sh
- conf/ref_databases.config
- conf/test.config
- docs/output.md
- lib/WorkflowAmpliseq.groovy
- modules/local/dada2_addspecies.nf
- modules/local/dada2_taxonomy.nf
- nextflow_schema.json
- workflows/ampliseq.nf
This PR allows Species assignment with DADA2's assignTaxonomy (results/dada2/ASV_tax.tsv) and exact match addSpecies as column "Species_exact" in (results/dada2/ASV_tax_species.tsv) for GTDB databases. This addresses https://github.com/nf-core/ampliseq/issues/351 & https://github.com/nf-core/ampliseq/issues/387.
The output changed in a way that Species assignment with assignTaxonomy will be performed and retained in case it is available from the taxonomy database. addSpecies will be run as well but not overwrite Species but instead adds a new column named Species_exact.
To run addSpecies, taxlevels (originating from --dada_assign_taxlevels or taxlevels from conf/ref_databases.config) must end with "Genus" or "Genus,Species".
Species assignment with assignTaxonomy works for databases:
- …
> assignTaxonomy Species assignment

- CHANGELOG.md
- modules.json
- workflows/ampliseq.nf
This adresses issue #475 
Added version information from DADA2_TAXONOMY to software versions, i.e. the lines
`DADA2_TAXONOMY:
R: 4.1.1
dada2: 1.22.0
`
are added to the file.
> Dada2 version in DADA2_TAXONOMY

- CHANGELOG.md
- conf/modules.config
- docs/output.md
- modules/local/dada2_quality.nf
- subworkflows/local/dada2_preprocessing.nf
- workflows/ampliseq.nf
This adds a QC plot also after all read preprocessing steps. Until now, there was FASTQC on raw data, DADA2's plotQualityProfile after trimming (cutadapt), and now there is also DADA2's plotQualityProfile after quality and length filtering, i.e. directly before ASV computation.
I have also added those DADA2 preprocessing & QC plotting into a separate workflow.
> produce QC plot after preprocessing

- CHANGELOG.md
- conf/ref_databases.config
- nextflow_schema.json
I added both an entry for the official GTDB files, as well as our new SBDI-GTDB files.
There are a lot of linting warnings about `when: condition has been removed`.
> GTDB R07-RS207

- CHANGELOG.md
- modules.json
- modules/local/picrust.nf
- modules/nf-core/modules/custom/dumpsoftwareversions/main.nf
- modules/nf-core/modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py
- modules/nf-core/modules/fastqc/main.nf
- modules/nf-core/modules/multiqc/main.nf
- modules/nf-core/modules/multiqc/meta.yml
- workflows/ampliseq.nf
Update software version as in https://github.com/nf-core/ampliseq/pull/468 but not QIIME2 (newer containers fail to run with docker).
> update nf-core modules and local picrust module

- subworkflows/local/dada2_preprocessing.nf
- workflows/ampliseq.nf
https://github.com/nf-core/ampliseq/pull/476  and https://github.com/nf-core/ampliseq/pull/477 seem to have introduced warnings such as 
> WARN: The operator `first` is useless when applied to a value channel which returns a single value by definition
and this is resolved here.
> Fix warnings

- main.nf
Uniform indent in main.nf, which was misaligned in template update 2.5.0/2.5.1
> correct website indent in main.nf

- CHANGELOG.md
- docs/usage.md
Came across a few stale links in usage.md. I have to remember that Markdown links that are working in Visual Studio Code might not work on the website.
> fix stale links

- CHANGELOG.md
- conf/ref_databases.config
- modules/local/qiime2_alphararefaction.nf
- modules/local/qiime2_ancom_asv.nf
- modules/local/qiime2_ancom_tax.nf
- modules/local/qiime2_barplot.nf
- modules/local/qiime2_classify.nf
- modules/local/qiime2_diversity_adonis.nf
- modules/local/qiime2_diversity_alpha.nf
- modules/local/qiime2_diversity_beta.nf
- modules/local/qiime2_diversity_betaord.nf
- modules/local/qiime2_diversity_core.nf
- modules/local/qiime2_export_absolute.nf
- modules/local/qiime2_export_relasv.nf
- modules/local/qiime2_export_reltax.nf
- modules/local/qiime2_extract.nf
- modules/local/qiime2_filterasv.nf
- modules/local/qiime2_filtertaxa.nf
- modules/local/qiime2_inasv.nf
- modules/local/qiime2_inseq.nf
- modules/local/qiime2_intax.nf
- modules/local/qiime2_train.nf
- modules/local/qiime2_tree.nf
Attempt to update to qiime2 2022.8, after docker failed with 2022.2 in https://github.com/nf-core/ampliseq/pull/468
> update to qiime2 2022.8

- CHANGELOG.md
- modules/local/format_taxonomy.nf
- modules/local/format_taxonomy_qiime.nf
Addresses https://github.com/nf-core/ampliseq/issues/502
> fix FORMAT_TAXONOMY_QIIME

- CHANGELOG.md
- conf/modules.config
- subworkflows/local/cutadapt_workflow.nf
- subworkflows/local/dada2_preprocessing.nf
- workflows/ampliseq.nf
Fix code to avoid warnings such as
`WARN: A process with name 'CUTADAPT_SUMMARY_DOUBLEPRIMER' is defined more than once in module script: github-ampliseq/ampliseq/./workflows/../subworkflows/local/cutadapt_workflow.nf -- Make sure to not define the same function as process`
that appear from nextflow version 22.10 onward.
Should not have any functional impact whatsoever.
> Fix warnings introduced in nextflow 22.10

- CHANGELOG.md
- conf/ref_databases.config
- modules/local/qiime2_alphararefaction.nf
- modules/local/qiime2_ancom_asv.nf
- modules/local/qiime2_ancom_tax.nf
- modules/local/qiime2_barplot.nf
- modules/local/qiime2_classify.nf
- modules/local/qiime2_diversity_adonis.nf
- modules/local/qiime2_diversity_alpha.nf
- modules/local/qiime2_diversity_beta.nf
- modules/local/qiime2_diversity_betaord.nf
- modules/local/qiime2_diversity_core.nf
- modules/local/qiime2_export_absolute.nf
- modules/local/qiime2_export_relasv.nf
- modules/local/qiime2_export_reltax.nf
- modules/local/qiime2_extract.nf
- modules/local/qiime2_featuretable_group.nf
- modules/local/qiime2_filterasv.nf
- modules/local/qiime2_filtertaxa.nf
- modules/local/qiime2_inasv.nf
- modules/local/qiime2_inseq.nf
- modules/local/qiime2_intax.nf
- modules/local/qiime2_train.nf
- modules/local/qiime2_tree.nf
This might fix https://github.com/nf-core/ampliseq/issues/516 _edit: unfortunately it doesnt!_
The size of the new container is 1/3 of the old container, already this is a stark argument.
> Update QIIME2 from 2022.8 to 2022.11

- CHANGELOG.md
- docs/usage.md
- modules/local/filter_len_asv.nf
- workflows/ampliseq.nf
Barrnap is now called also with fasta input. In addition, although not tested, filtering should work with fasta input.
> Run barrnap with fasta

- CHANGELOG.md
- bin/taxref_reformat_gtdb.sh
- bin/taxref_reformat_standard.sh
- bin/taxref_reformat_unite.sh
- conf/ref_databases.config
- conf/test_fasta.config
- modules/local/barrnapsummary.nf
- modules/local/dada2_addspecies.nf
- modules/local/dada2_taxonomy.nf
- nextflow.config
- nextflow_schema.json
Removed any modification of the number of taxonomic levels in reference databases for DADA2 classification:
- SILVA and RDP had the duplication of the first field removed (bin/taxref_reformat_standard.sh)
- GTDB had an additional level of "Archaea" or "Bacteria" removed (bin/taxref_reformat_gtdb.sh)
- UNITE had "Eukaryota" removed (bin/taxref_reformat_unite.sh)
- the default was changed to the majority of databases ("Kingdom,Phylum,Class,Order,Family,Genus,Species")
> Remove taxonomic adjustments

- CHANGELOG.md
- bin/sbdiexportreannotate.R
- bin/summarize_barrnap.py
- modules/local/barrnapsummary.nf
- workflows/ampliseq.nf
Fix so empty output from barrnap can be handled by sbdi_export, added warnings and error messages id barrnap fails to find rRNA sequences. This adresses #552
> Fix empty barrnap output

- CHANGELOG.md
- bin/parse_dada2_taxonomy.r
Addresses a problem that occurs in 2.5.0 that choosing [silva_132.18s.99_rep_set.dada2.fa.gz](https://zenodo.org/record/1447330) with `--dada_ref_tax_custom`, 
i.e. with `nextflow run nf-core/ampliseq -r 2.5.0 -profile singularity --input samplesheet.tsv --dada_assign_taxlevels "Eukaryota,Opisthokonta,Holozoa,Metazoa,Tetrapoda,Mammalia,Homo,Genus" --dada_ref_tax_custom "https://zenodo.org/record/1447330/files/silva_132.18s.99_rep_set.dada2.fa.gz" --skip_dada_addspecies --outdir results`
the taxonomic strings contain `#` and `'` and will fail to be transferred to QIIME2. This PR fixes the issue.
> Let QIIME2 accept special symbols in taxonomy strings

- CHANGELOG.md
- modules/local/dada2_stats.nf
The input/DADA2_input column is named differently when using single end data compared to paired end, I suggest to use "DADA2_input" in both cases. I cannot find any conflicts in the ampliseq code.
> Make header in overall_summary consistent

- CHANGELOG.md
- CITATIONS.md
- conf/modules.config
- conf/test.config
- conf/test_pplace.config
- docs/output.md
- lib/WorkflowAmpliseq.groovy
- modules/local/format_pplacetax.nf
- modules/local/qiime2_intree.nf
- nextflow.config
- nextflow_schema.json
- subworkflows/local/qiime2_diversity.nf
- subworkflows/local/qiime2_export.nf
- workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/561
Taxonomic tree and taxonomic annotation from phylogenetic placement are now picked up and used in downstream (QIIME2) analysis. 
The additional code in `FORMAT_PPLACETAX` uses only the taxonomic annotation from Gappa that
```
- has the lowest LWR, 
- if multiple, 
- if identical it will choose the first one, 
- if not identical, it will choose the one with less taxonomic entries, 
- if same number of taxonomic entries, it will remove entries until they are identical, 
- if all removed it will add a `NA`. 
```
I searched, tested and dismissed several pre-made code/commands/functions for this, such as from R's stringi or stringr packages, so I made the custom code.
> use phylogenetic placement output in qiime

- CHANGELOG.md
- workflows/ampliseq.nf
I obviously broke NFCORE_AMPLISEQ:AMPLISEQ:QIIME2_DIVERSITY:QIIME2_TREE and therefore no QIIME2_DIVERSITY:* was executing with `-profile test` (or any other). That happend in https://github.com/nf-core/ampliseq/pull/567, because I fiddled with the tree info, found that out [here](https://github.com/nf-core/ampliseq/pull/577#pullrequestreview-1420354549). This PR fixes it (pretty simple...).
> fix diversity analysis

- CHANGELOG.md
- bin/taxref_reformat_pr2.sh
Closes https://github.com/nf-core/ampliseq/issues/593.
> PR2 exact species assignment now without taxa ending with sp.

- CHANGELOG.md
- README.md
- assets/report_template.Rmd
- modules/local/summary_report.nf
- workflows/ampliseq.nf
Changes:
- add SBDI export and phyloseq output to summary report
- update changelog with https://github.com/nf-core/ampliseq/pull/615
- add @a4000 to acknowledgements
> add SBDI export and phyloseq output to summary report

- docs/usage.md
Fix small typo in quick start command which will make the command fail...
> fix typo in quick start command

- CHANGELOG.md
- assets/report_template.Rmd
- modules/local/summary_report.nf
- workflows/ampliseq.nf
Update pipeline report with VSEARCH cluster and add a methods section that can be (almost, missing software versions) copied into a manuscript.
> Manuscript methods section and VSEARCH cluster to pipeline report

- CHANGELOG.md
- workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/627
This PR attempts the fix by adding two sanity checks after reading the sample sheet that will raise a clear error with the request to change sampleIDs. I did think about fixing it in the [problematic code line of the renaming module](https://github.com/nf-core/ampliseq/blob/3b252d263d101879c7077eae94a7a3d714b051aa/modules/local/rename_raw_data_files.nf#L14) that picks up additionally to renamed files also an original input file, but I didn't come up with a feasible solution (all my solutions would require a re-factoring of multiple other modules to correct the sample ID).
Using the sample sheet `samplesheet.tsv` with content
```
sampleID	forwardReads	reverseReads
S127_02	S127_01.fastq.gz	S127_02.fastq.gz
S115	S115_1.fastq.gz …
```
> Prevent rare error with sample sheet edge case

- CHANGELOG.md
- modules/local/qiime2_diversity_core.nf
There were reports that QIIME2 diversity failed when a GPU was listed as available in an compute environment but not accessible for the process. This fixed it.
> disable GPU for UNIFRAC

- CHANGELOG.md
- conf/test_failed.config
- tests/pipeline/failed.nf.test
- workflows/ampliseq.nf
This is a bug fix: 
`nextflow run nf-core/ampliseq -r 2.5.0 -profile test_reftaxcustom,singularity --outdir results --dada_ref_tax_custom_sp false --skip_dada_addspecies`
was fine but 
`nextflow run nf-core/ampliseq -r 2.6.1 -profile test_reftaxcustom,singularity --outdir results --dada_ref_tax_custom_sp false --skip_dada_addspecies`
failed with 
`ERROR ~ No such variable: ch_addspecies`
Obviously that function was broken after introduction, so I added a test in the new `test_failed.conf` that should prevent that in future.
>  Fix --dada_ref_tax_custom without --dada_ref_tax_custom_sp

- CHANGELOG.md
- assets/report_template.Rmd
- modules/local/summary_report.nf
- subworkflows/local/dada2_preprocessing.nf
- workflows/ampliseq.nf
Ironing out issues in the pipeline summary report, custom taxonomic databases weren't properly reported (NA).
Additionally moved a code snippet from `ampliseq.nf` to a subworkflow, a purely cosmetic change.
> Update pipeline summary report

- CHANGELOG.md
- modules/local/qiime2_alphararefaction.nf
- modules/local/qiime2_ancom_asv.nf
- modules/local/qiime2_ancom_tax.nf
- modules/local/qiime2_barplot.nf
- modules/local/qiime2_classify.nf
- modules/local/qiime2_diversity_adonis.nf
- modules/local/qiime2_diversity_alpha.nf
- modules/local/qiime2_diversity_beta.nf
- modules/local/qiime2_diversity_betaord.nf
- modules/local/qiime2_diversity_core.nf
- modules/local/qiime2_export_absolute.nf
- modules/local/qiime2_export_relasv.nf
- modules/local/qiime2_export_reltax.nf
- modules/local/qiime2_extract.nf
- modules/local/qiime2_featuretable_group.nf
- modules/local/qiime2_filtersamples.nf
- modules/local/qiime2_filtertaxa.nf
- modules/local/qiime2_inasv.nf
- modules/local/qiime2_inseq.nf
- modules/local/qiime2_intax.nf
- modules/local/qiime2_intree.nf
- modules/local/qiime2_train.nf
- modules/local/qiime2_tree.nf
- subworkflows/local/dada2_taxonomy_wf.nf
This fixes the issue with nextflow version 23.10.0 on some systems, see https://github.com/nf-core/ampliseq/issues/654
> Fix nextflow version 23.10.0 with QIIME2

- CHANGELOG.md
- modules/local/qiime2_alphararefaction.nf
- modules/local/qiime2_ancom_asv.nf
- modules/local/qiime2_ancom_tax.nf
- modules/local/qiime2_barplot.nf
- modules/local/qiime2_classify.nf
- modules/local/qiime2_diversity_adonis.nf
- modules/local/qiime2_diversity_alpha.nf
- modules/local/qiime2_diversity_beta.nf
- modules/local/qiime2_diversity_betaord.nf
- modules/local/qiime2_diversity_core.nf
- modules/local/qiime2_export_absolute.nf
- modules/local/qiime2_export_relasv.nf
- modules/local/qiime2_export_reltax.nf
- modules/local/qiime2_extract.nf
- modules/local/qiime2_featuretable_group.nf
- modules/local/qiime2_filtersamples.nf
- modules/local/qiime2_filtertaxa.nf
- modules/local/qiime2_inasv.nf
- modules/local/qiime2_inseq.nf
- modules/local/qiime2_intax.nf
- modules/local/qiime2_intree.nf
- modules/local/qiime2_train.nf
- modules/local/qiime2_tree.nf
Moved the conda check to script section to avoid any problems when running with conda, see https://github.com/nf-core/modules/issues/3683
- Moved conda-check to script-section
- replaced `exit 1` with `error()`
> Move conda check to script section

- CHANGELOG.md
- modules/local/summary_report.nf
Qiime2 part of the summary report tries to include information from the chosen qiime reference database. In cases where a classifier is used directly, this information may not be available, so I've added to check to see whether it is or not.
> Fix qiime2 taxonomy part of summary report using unavailable information.

- CHANGELOG.md
- assets/report_template.Rmd
- subworkflows/local/parse_input.nf
Minor improvements to error messages and pipeline report:
- one error message referred to `--input` when it should be `--input_folder`
- report folder `<outdir>/input` only when its actually created (when there is a metadata sheet and/or sample sheet)
- reporting % discarded reads by cutadapt trimming were not reported (`NA`) when the percentages were less than `10.0%`.
> Improved pipeline summary report & error message

- CHANGELOG.md
- conf/modules.config
- docs/usage.md
- nextflow.config
- nextflow_schema.json
1. Added two parameters:
- `--dada_addspecies_allowmultiple`: Defines the behavior when multiple exact matches against different species are returned. By default only unambiguous identifications are returned. If TRUE, a concatenated string of all exactly matched species is returned.
- `--dada_taxonomy_rc`: Reverse-complement of each sequences will be used for classification if it is a better match to the reference sequences than the forward sequence.
3. Updated `usage.md `to explain that `--dada_taxonomy_rc` is recommended with `--dada_ref_taxonomy gtdb` according to https://zenodo.org/records/4735821:
> Another concern that was raised was the orientation of the DB sequences, to get past this problem please use the tryRC = TRUE argument in the assignTaxonomy command within DADA2, this …
> Add two parameters for taxonomic classification with DADA2

- CHANGELOG.md
- README.md
This fixes the top of the README where some badges were not properly rendered due to a missing empty line.
> Fix README

- CHANGELOG.md
- bin/filt_clusters.py
- modules/local/filter_clusters.nf
Closes https://github.com/nf-core/ampliseq/issues/696
I have not confirmed myself whether that change allows for more clusters to pass.
My python skills are horrible, so I need some serious opinion whether that seems fine. Tests pass and test files seem fine as well.
> fix vsearch cluster filtering

- CHANGELOG.md
- modules/local/dada2_denoising.nf
- modules/local/dada2_err.nf
Closes https://github.com/nf-core/ampliseq/issues/706
> Fix file sorting with radix method

- CHANGELOG.md
- assets/report_template.Rmd
- conf/modules.config
- docs/output.md
- modules/local/filter_len.nf
- workflows/ampliseq.nf
Sequences below 50bp cannot be used by DADA2 and most likely also other kmer-based classification methods fail with too short sequences (see `https://github.com/benjjneb/dada2/issues/601`). This can be usually easily prevented with `--min_len_asv`, but not when ITSx is used (because this is after `--min_len_asv` is appplied). Therefore, another length filtering step with 50bp min length is added here. The minimum value of 50 is not represented by a parameter but can be adjusted via a config, if required.
Closes https://github.com/nf-core/ampliseq/issues/704.
> Require a minimum sequence length of 50bp after ITSx

- CHANGELOG.md
- modules.json
- modules/nf-core/pigz/uncompress/main.nf
- modules/nf-core/pigz/uncompress/pigz-uncompress.diff
Whenever version 2.8.0 of the pipeline started, the message `unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException` appeared, causing confusion. The cause was a missing `\` in a nf-core module, thats now fixed.
> Fix groovyjarjarantlr4.v4.runtime.LexerNoViableAltException

- .github/workflows/download_pipeline.yml
- CHANGELOG.md
On release, a test called `Test successful pipeline download with 'nf-core download' / download (pull_request)` is executed and fails. 
**There seem to be two reasons:**
(1) The pipeline doesnt have in all modules a `stub: `section, therefore using `-stub` will fail
(2) There is a problem with downloading the QIIME2 image, see [here](https://github.com/nf-core/ampliseq/actions/runs/8463857822/job/23187726903?pr=725#step:7:47). This works locally and I do not know why it fails in the test.
**Solutions added here:**
(1) Implemented https://github.com/nf-core/tools/pull/2846
(2) Added `--skip_qiime` to remove the need for the QIIME2 container
> fix Download Pipeline Workflow

- CHANGELOG.md
- modules/local/sidle_align.nf
- modules/local/sidle_dbextract.nf
- modules/local/sidle_dbfilt.nf
- modules/local/sidle_dbrecon.nf
- modules/local/sidle_filttax.nf
- modules/local/sidle_in.nf
- modules/local/sidle_indb.nf
- modules/local/sidle_indbaligned.nf
- modules/local/sidle_seqrecon.nf
- modules/local/sidle_tablerecon.nf
- modules/local/sidle_taxrecon.nf
- modules/local/sidle_treerecon.nf
- modules/local/sidle_trim.nf
For a new software (Sidle) I produced a container and deposited it at dockerhub. The processes that use that software did so with `container 'docker.io/d4straub/pipesidle:0.1.0-beta'`. My proposal to put the tool (pypi packaged) to conda was rejected by the developer of said tool. I generated the container with [Dockerfile](https://github.com/d4straub/pipesidle/blob/83600d3b4068526e19d8f9db7a1c716c2a7c5c0a/Dockerfile) & [environment.yml](https://github.com/d4straub/pipesidle/blob/83600d3b4068526e19d8f9db7a1c716c2a7c5c0a/environment.yml). This container was now pushed to `quay.io/nf-core`, therefore now retrieved by `container 'nf-core/pipesidle:0.1.0-beta'`.
> Retrieve Sidle container from quay.io/nf-core instead of docker.io/d4straub

- CHANGELOG.md
- docs/output.md
- subworkflows/local/dada2_preprocessing.nf
This addresses https://github.com/nf-core/ampliseq/issues/733 and https://github.com/nf-core/ampliseq/issues/746.
> Fix misleading error message and documentation

- CHANGELOG.md
- workflows/ampliseq.nf
The taxonomic barplot is now also created when no metadata is supplied.
Closes https://github.com/nf-core/ampliseq/issues/738
> Create barplot also without metadata

- CHANGELOG.md
- conf/ref_databases.config
- nextflow_schema.json
- subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
Finally, last year's release of GTDB in SBDI-GTDB vetted format.
> sbdi-gtdb=R08-RS214-1 (r214)

- CHANGELOG.md
- modules/local/dada2_stats.nf
`overall_summary.tsv` had sometimes misleading numbers in 2.9.0. This was due to a new sorting method added in https://github.com/nf-core/ampliseq/pull/717 (necessary due to bad forward & reverse read pairing due to edge case sample names). 
This PR makes sure that all tables that are merged are identically sorted (merged by `cbind` rather than `merge` due to different row names (contain sampleID), e.g. `sample1.trimmed_1.trim.fastq.gz` & `sample1_1.filt.fastq.gz` & `sample1_2.filt.fastq.gz`).
I also considered correcting the row names for each table and subsequently apply `merge`, but because row names are so divers, that seems not great. I do have the feeling correcting row names and use `merge` might be safer, but I couldnt find any example where it would matter, but I am open to …
> Fix sorting in overall_summary.tsv

- CHANGELOG.md
- bin/taxref_reformat_gtdb.sh
- conf/ref_databases.config
- nextflow_schema.json
- subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
Adding GTDB R09-RS220 as choice for --dada_ref_taxonomy.
> add GTDB RS220

- CHANGELOG.md
- docs/output.md
- nextflow_schema.json
Renamed sections with `differential abundance testing` to `differential abundance analysis` to make documentation uniform. Also a link from usage to parameter documentation was broken due to this.
> fix differential abundance analysis documentation

- CHANGELOG.md
- README.md
The TIP and WARNING boxes in the README were not rendered as expected on the webpage, that should fix it.
Purly cosmetic changes, so I am skipping the review here (but automatic tests were fine).
> Cosmetic improvements of the README

- CHANGELOG.md
- docs/output.md
- nextflow_schema.json
ASV post processing includes ASV clustering and filtering and had changes. This part is updated now in the output documentation.
Additionally, descriptions of sections in the parameters documentation were added.
> Update documentation: ASV post processing & parameters description

- CHANGELOG.md
- conf/ref_databases.config
- docs/usage.md
- subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
- workflows/ampliseq.nf
Fix for https://github.com/nf-core/ampliseq/issues/767: Reference taxonomy database values were not properly validated in versions 2.9.0 and 2.10.0
Update docs for removed UNITE databases for QIIME2 in https://github.com/nf-core/ampliseq/pull/766.
> Fix --*_ref_taxonomy validation

- CHANGELOG.md
- modules/local/qiime2_ancom_tax.nf
- modules/local/qiime2_ancombc_asv.nf
- modules/local/qiime2_ancombc_tax.nf
- modules/local/qiime2_diversity_adonis.nf
- modules/local/qiime2_diversity_beta.nf
- modules/local/qiime2_seqfiltertable.nf
Closes https://github.com/nf-core/ampliseq/issues/789
I removed or replaced all white spaces in process tags.
> Remove white space in process tags

- CHANGELOG.md
- conf/ref_databases.config
The files used to assign SH for UNITE 9.0 are missing some taxonomies due to an update of the PlutoF API that partially broke the scripts used. This PR gives links to the new, corrected files.
> Fix SH files for unite9

- CHANGELOG.md
- modules/local/format_pplacetax.nf
Issue #808 reports a missing R library declaration in the `FORMAT_PPLACETAX` module. I couldn't reproduce the error, but the code does not look like it should work, so I fixed it anyway.
> Fix missing library

- CHANGELOG.md
- docs/usage.md
- subworkflows/local/parse_input.nf
- update the`usage.md` sections Metadata and Sample input to remove the dashes (closes #821)
- update TOC in `usage.md`
- check if sample id extracted from input dir are only composed by letters, numbers and underscores
> fix: rm sampleid dashes in doc and add check for directory input

- CHANGELOG.md
- bin/taxref_reformat_gg2.sh
- conf/ref_databases.config
- docs/usage.md
- nextflow_schema.json
- subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
Closes https://github.com/nf-core/ampliseq/issues/828
I tested locally and worked out fine. I didnt try to activate it in any test, I assume (but dont know) that the DB is too large for github CI.
> Add Greengenes2 for taxonomic classification with DADA2

- CHANGELOG.md
- conf/modules.config
- docs/usage.md
- nextflow.config
- nextflow_schema.json
- subworkflows/local/sidle_wf.nf
- subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
- workflows/ampliseq.nf
Reorganization of input for custom databases for SIDLE, i.e. multi-region analysis such as 5R.
Now the multiple sequence alignment file for reference sequences has its own parameter and is optional instead of required. That allows much easier usage of custom reference databases, because only taxonomic strings and reference sequences are required.
For this, `sidle_ref_tax_custom` was changed so that it accepts only the taxonomy file instead of requiring 3 files. New params are `sidle_ref_seq_custom` and `sidle_ref_aln_custom` that accept the other 2 files that were previously required by `sidle_ref_tax_custom`. `sidle_ref_degenerates` and `sidle_ref_cleaning` allow easier manipulation of the custom database than before.
> Allow multiregion analysis without alignment file

- CHANGELOG.md
- modules.json
- modules/nf-core/vsearch/cluster/environment.yml
- modules/nf-core/vsearch/cluster/main.nf
- modules/nf-core/vsearch/cluster/tests/tags.yml
Fixing bug https://github.com/nf-core/ampliseq/issues/869 
I have pulled the updated nf-core/modules vsearc/cluster module into the dev branch of ampliseq. 
This should fix an arguments too long error froma wildcard expansion.
- [ yes] This comment contains a description of changes (with reason).
- [ n/a] If you've fixed a bug or added code that should be tested, add tests!
- [ n/a] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md)
- [ n/a] If necessary, also make a PR on the nf-core/ampliseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ yes] Make sure your code lints (`nf-core pipelines lint`).
- [ yes] Ensure the …
> pulling and updated vsearch/cluster module from nf-core

- .github/workflows/awsfulltest.yml
- .nf-core.yml
- CHANGELOG.md
- ro-crate-metadata.json
Merging changes from nf-core template 3.2.1, essentially bug fixes.
I didnt really understand why the template update attempted to revert the pipeline version from 2.14.0dev to 2.13.0, I rejected most of those changes. However, the ro-crate-metadata.json was changed as well, not sure if that should be reverted.
> Merged changes from nf-core template 3.2.1

- CHANGELOG.md
- conf/ref_databases.config
- nextflow_schema.json
- subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
Closes https://github.com/nf-core/ampliseq/issues/877
> Add GTDB R10-RS226

- CHANGELOG.md
- modules/local/dada2_splitregions.nf
Closes https://github.com/nf-core/ampliseq/issues/891
> fix DADA2_SPLITREGIONS with one sample

- CHANGELOG.md
- assets/report_template.Rmd
- conf/modules.config
- docs/usage.md
- modules/local/summary_report.nf
- nextflow.config
- nextflow_schema.json
- workflows/ampliseq.nf
Adds a parameter,`--truncq`, that allows read truncation by quality score, where each read is truncated at the first instance of a quality score less than or equal to `truncq`. The parameter is equivalent to `truncQ` in DADA2's [filterAndTrim](https://rdrr.io/bioc/dada2/man/filterAndTrim.html) method. `truncq` defaults to 2, which was already the default in the DADA2_FILTNTRIM module (https://github.com/nf-core/ampliseq/blob/2.14.0/conf/modules.config#L142).
In the DADA2 filtering and trimming steps, the truncQ parameter is applied before read length truncation for both [single](https://github.com/benjjneb/dada2/blob/ab844341c47d8fe922c2e9dea849bf2167bcd445/R/filter.R#L669-L684) and [paired](https://github.com/benjjneb/dada2/blob/ab844341c47d8fe922c2e9dea849bf2167bcd445/R/filter.R#L1031-L1 …
> Add truncq parameter for quality score-based read truncation

- CHANGELOG.md
- assets/report_template.Rmd
- conf/modules.config
- docs/usage.md
- modules/local/summary_report.nf
- nextflow.config
- nextflow_schema.json
This PR adds a new parameter, dada_min_boot, that corresponds exactly with minBoot in DADA2's [assignTaxonomy](https://rdrr.io/bioc/dada2/man/assignTaxonomy.html) method. This parameter specifies a minimum bootstrap confidence (out of 100 trials) needed in order to assign a taxonomic level. This can be helpful in order to filter out assignments for ASVs that are likely too specific. E.g. An ASV was assigned to the incorrect species with confidence 55 (0.55), which is quite low, but was assigned to the correct genus level with confidence 75 (0.75). By setting dada_min_boot to 60 (0.60) in this example, the reported assignment would be to the genus level. Users can adjust dada_min_boot based on their own observations concerning what threshold they begin to see inaccurate assignments.
This …
> Add min boot param
