.travis.yml, Dockerfile, Singularity, environment.yml, nextflow.config
This is to prepare for release 1.0 of "Olive Steel Panda".
**Learn more about contributing:** https://github.com/nf-core/rrna-ampliseq/tree/master/.github/CONTRIBUTING.md
=> Prepare for release 1.0 "Olive Steel Panda"

conf/binac.config, conf/cfc.config, main.nf, nextflow.config
This adds channels for all input variables, and adds MATPLOTLIBRC as ENV for all processes requiring it. 
**Learn more about contributing:** https://github.com/nf-core/rrna-ampliseq/tree/master/.github/CONTRIBUTING.md
=> Channels for inputs, MATPLOTLIBRC everywhere

nextflow.config
This addresses the issue with the centralized configs that was present this morning.
=> Fixing centralized configs

nextflow.config
Config loading was twice in...
=> Don#t load configs twice

.github/workflows/ci.yml, .travis.yml, CHANGELOG.md, Dockerfile, README.md, conf/base.config, docs/output.md, docs/usage.md, environment.yml, main.nf, nextflow.config
This fixes an issue with #116 , updates the README a little. Nothing else changed :+1:
=> PR for 1.1.2 - Bugfix release

README.md, docs/usage.md
This is just a minor docs update
**Learn more about contributing:** https://github.com/nf-core/ampliseq/tree/master/.github/CONTRIBUTING.md
=> docs update

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
I'd like to make a small release in order to accommodate recent quality-of-use updates (manifest input, safety net for auto parameter choosing), template update and citation reference.
=> Prepare 1.1.3

.github/workflows/ci.yml, CHANGELOG.md, conf/base.config, docs/output.md
Adress issues raised in PR #178
=> Adress issues raised in PR for 1.1.3

.github/workflows/awsfulltest.yml, .github/workflows/awstest.yml, .github/workflows/ci.yml, CHANGELOG.md
=> Update github actions

main.nf
Changed deprecated baseDir to projectDir in main.nf to get rid of a (non-fatal) warning message.
=> Remove baseDir occurrences

CHANGELOG.md, main.nf, nextflow.config, nextflow_schema.json
Instead of having `--unite` to specify a unite-database it should now be passed as a string to `--taxon_reference`. `--taxon_reference` only works for silva and unite at the moment.
=> Change unite flag

nextflow.config, nextflow_schema.json
=> Restore defaults for max_cpus, max_memory and max_time

CHANGELOG.md, main.nf
=> Don't fetch taxonomy/create classifier when run with --skip_taxonomy

README.md
Dear all,
it's time to credit contributors. Please check if you are fine with the wording. I sorted alphabetically. Let me know if you have any suggestions.
Thanks a lot for your contributions!
=> Credit contributors

CHANGELOG.md, main.nf, nextflow_schema.json
This solves #211.
I also quickly unified indentation for the help message.
=> Expose quality filter option maxEE also for Illumina data

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, bin/scrape_software_versions.py, environment.yml, main.nf, nextflow.config
This PR changes version name to prepare for release 1.2.0
=> Prepare for 1.2.0 release

README.md
Improve README.md for 1.2.0 release adressing feedback in #216 .
=> Improve README.md for 1.2.0 release

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
Change version from 1.2.0 to 1.3.0dev after release of 1.2.0.
=> Bump version to 1.3.0dev

bin/parse_dada2_taxonomy.r, modules/local/qiime2_intax.nf, workflows/ampliseq.nf
DADA2 taxonomic classification is forwarded to QIIME2 downstream analysis preferentially over QIIME2 taxonomic classification. QIIME2 taxonomic classification is still in the pipeline but not used further.
=> forward preferentially DADA2 classification to downstream analysis

.github/workflows/ci.yml
this should fix stalling of "Run workflow tests", lets see!
=> fix CI tests

bin/taxref_reformat_gtdb.sh, bin/taxref_reformat_unite.sh
Added a script for Unite files, only tested with a single fungi file.
Output files are now `assignTaxonomy.fna` and `addSpecies.fna` from both the unite and the gtdb scripts.
=> Unite script

.github/workflows/ci.yml
This is supposed to solve  #200
=> Parallellise CI tests for profiles

CHANGELOG.md, bin/cutadapt_summary.py, conf/modules.config, docs/output.md, modules/local/cutadapt_summary.nf, modules/local/cutadapt_summary_merge.nf, subworkflows/local/cutadapt_workflow.nf, workflows/ampliseq.nf
This produces a summary file for cutadapt. This is a prerequisite to solving #185.
=> cutadapt into own workflow and add cutadapt summary file

CHANGELOG.md, conf/base.config, docs/output.md, modules/local/dada2_denoising.nf, modules/local/qiime2_ancom_asv.nf, nextflow_schema.json, subworkflows/local/qiime2_ancom.nf, workflows/ampliseq.nf
- increase runtime for processes dada2_denoising and qiime2_ancom_asv
- remove `--reference_database`, `--dereplication`, `--name` from nextflow.schema
- return empty channel when no appropriate metadatacolumn is found by METADATA_ALL, avoiding error code 1
=> Dsl2 small fixes

conf/test.config, conf/test_full.config, modules/local/metadata_all.nf, modules/local/qiime2_ancom_asv.nf, modules/local/qiime2_ancom_tax.nf, nextflow.config, nextflow_schema.json, workflows/ampliseq.nf
The following points are supposed to resolve suggestions in #232 
- adjust qiime2_ancom_tax & qiime2_ancom_asv process resources
- filter low abundance or low prevalence ASVs in `test.config` and `test_full.config` to speed up downstream analysis of tests
- change default of params classifier, metadata, metadata_category so that these wont be listed in the summary when with standard settings
=> Dsl2 adjust ancom and tests

modules/local/metadata_all.nf, workflows/ampliseq.nf
Supposed to resolve suggestions in #232
=> simplify params testing

.gitignore, bin/parse_dada2_taxonomy.r, bin/taxref_reformat_unite.sh, conf/ref_databases.config, modules/local/cutadapt_summary_merge.nf, modules/local/dada2_addspecies.nf, modules/local/dada2_merge.nf, modules/local/dada2_taxonomy.nf, modules/local/qiime2_intax.nf, subworkflows/local/cutadapt_workflow.nf, workflows/ampliseq.nf
- [x ] This comment contains a description of changes (with reason).
- [x ] If you've fixed a bug or added code that should be tested, add tests!
- [?] Make sure your code lints (`nf-core lint .`).
* @jtangrot wanted both the Unite fungi and Unite all eukaryotes databases from PlutoF, so I added the latter. The Unite databases are now known as "unite-fungi" and "unite-alleuk", with or without "=8.2". I deliberately chose to delete "unite" to make sure one explicitly calls one or the other.
* She also wanted to switch to the "developer" versions, so I did that too. We should remember to document that...
=> Unite updates

CHANGELOG.md, conf/test_pacbio_its.config, docs/output.md, main.nf, nextflow.config, nextflow_schema.json, subworkflows/local/parse_input.nf, workflows/ampliseq.nf
When adding the updates of nf-core/tools 1.13.3 in #253, parameter validation got lost in the merge conflicts. I added that now. Unfortunately that meant that parameters needed a change, all `CamelCase` parameters were therefore converted into `snake_case` stye, see CHANGELOG.
=> add parameter validation

modules/local/filter_stats.nf, modules/local/rename_raw_data_files.nf, modules/local/trunclen.nf, nextflow.config
Corrected names of conda packages to make it possible to use conda profile. Also removed reference to environment.yml in nextflow.config, as that file is not present/used any more. BTW, the fact that environment.yml is missing results in a lint warning, don't know if that's relevant. The workflow seems to run as it should with  -profile test,conda
=> Minor changes to make conda work

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, CHANGELOG.md, README.md, lib/NfcoreSchema.groovy, main.nf, nextflow.config, nextflow_schema.json
This is an update to nf-core tools 1.14
=> Merging template updates 1.14

CHANGELOG.md, nextflow.config, nextflow_schema.json, workflows/ampliseq.nf
Here are two small changes that were discussed in the slack channel:
- added `--skip_qiime` to prevent all QIIME2 steps incl. software download
- changed default of `--sample_inference` from `pooled` to `independent` to be more consistent with earlier versions
=> Discussed changes

CHANGELOG.md, nextflow.config
=> bump version to 2.0.0

CHANGELOG.md
This is an update of CHANGELOG.md, only to update release dates.
=> add release dates

CHANGELOG.md, nextflow.config
Bump up the pipeline version number in the development branch.
=> Bump version to 2.1.0dev

CHANGELOG.md, bin/taxref_reformat_unite.sh, conf/ref_databases.config, nextflow_schema.json
I added the new releases of PR2 and Unite.
=> Pr2 unite new rels

.editorconfig, .github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/linting.yml, CHANGELOG.md, README.md, bin/scrape_software_versions.py, lib/NfcoreTemplate.groovy, workflows/ampliseq.nf
=> Merging template updates 2.1

.github/workflows/ci.yml
I added `test_single` to the list of tests that gets run automatically.
=> Added test_single to automatic tests

CHANGELOG.md, CITATIONS.md, bin/taxref_reformat_sbdi-gtdb.sh, conf/ref_databases.config, nextflow_schema.json
- [] Usage Documentation in `docs/usage.md` is updated.
We have curated the GTDB 16S database with Sativa. This is now available as `sbdi-gtdb` with `--dada_ref_databases`.
=> Added new DADA2 reference db: sbdi-gtdb

conf/test_fasta.config, nextflow.config
I added a test case for fasta input.
=> Test case for fasta input

CHANGELOG.md, conf/modules.config, conf/ref_databases.config, docs/output.md, modules/local/format_taxonomy.nf, modules/local/format_taxonomy_qiime.nf, subworkflows/local/qiime2_preptax.nf, workflows/ampliseq.nf
This is supposed to solve #309
=> export reference taxonomy citation into file

CHANGELOG.md, modules/local/cutadapt_summary_merge.nf, modules/local/dada2_addspecies.nf, modules/local/dada2_denoising.nf, modules/local/dada2_dereplicate.nf, modules/local/dada2_err.nf, modules/local/dada2_filtntrim.nf, modules/local/dada2_merge.nf, modules/local/dada2_quality.nf, modules/local/dada2_rmchimera.nf, modules/local/dada2_stats.nf, modules/local/dada2_taxonomy.nf, modules/local/merge_stats.nf, modules/local/metadata_all.nf, modules/local/metadata_pairwise.nf
=> Update DADA2 from 1.18 to 1.20

modules/local/dada2_denoising.nf, modules/local/qiime2_alphararefaction.nf, modules/local/qiime2_ancom_asv.nf, modules/local/qiime2_ancom_tax.nf, modules/local/qiime2_barplot.nf, modules/local/qiime2_classify.nf, modules/local/qiime2_diversity_alpha.nf, modules/local/qiime2_diversity_beta.nf, modules/local/qiime2_diversity_betaord.nf, modules/local/qiime2_diversity_core.nf, modules/local/qiime2_export_absolute.nf, modules/local/qiime2_export_relasv.nf, modules/local/qiime2_export_reltax.nf, modules/local/qiime2_extract.nf, modules/local/qiime2_filterasv.nf, modules/local/qiime2_filtertaxa.nf, modules/local/qiime2_inasv.nf, modules/local/qiime2_inseq.nf, modules/local/qiime2_intax.nf, modules/local/qiime2_train.nf, modules/local/qiime2_tree.nf, modules/nf-core/modules/cutadapt/main.nf
=> Revert "Cutadapt fix and qiime2 container version change"

CHANGELOG.md, CITATIONS.md, conf/modules.config, docs/output.md, modules/local/qiime2_diversity_adonis.nf, nextflow.config, nextflow_schema.json, subworkflows/local/qiime2_diversity.nf
This is testing for metadata feature importance and significance in beta diversity distances. Quite interesting in my opinion and an easy addition within QIIME2.
=> Add ADONIS test

CHANGELOG.md, conf/ref_databases.config, nextflow_schema.json
I added `sbdi-gtdb=R06-RS202-3` to the list of DADA2 reference taxonomy databases. This is also the new default version for `sbdi-gtdb`.
=> Added sbdi-gtdb version 3

modules/local/itsx_cutasv.nf
ITSx was not taking any `args` from the `conf/modules.config`. This should fix it.
=> fix ITSx args

CHANGELOG.md, docs/usage.md
Closes https://github.com/nf-core/ampliseq/issues/353
=> clarify single-end input docs

docs/output.md, modules/local/combine_table.nf, modules/local/cutadapt_summary_merge.nf, modules/local/dada2_addspecies.nf, modules/local/dada2_denoising.nf, modules/local/dada2_err.nf, modules/local/dada2_filtntrim.nf, modules/local/dada2_merge.nf, modules/local/dada2_rmchimera.nf, modules/local/dada2_stats.nf, modules/local/dada2_taxonomy.nf, modules/local/filter_stats.nf, modules/local/format_taxresults.nf, modules/local/merge_stats.nf, modules/local/metadata_all.nf, modules/local/metadata_pairwise.nf, modules/local/picrust.nf, modules/local/rename_raw_data_files.nf, modules/local/sbdiexport.nf, modules/local/sbdiexportreannotate.nf, modules/local/trunclen.nf, nextflow.config, nextflow_schema.json, workflows/ampliseq.nf
This addresses reviewer comments in https://github.com/nf-core/ampliseq/pull/379
Three kind of fixes:
- versions output
- grammar in docs
- descriptions & defaults in nextflow_schema.json
I did not output redundant software versions. I.e. when a software uses the same container it will be listed only once in the report. I think thats not perfect, but listing redundant software versions for a plethora of tools also doesn't help, in my opinion.
=> Adressing reviewer comments for release 2.2.0 PR

CHANGELOG.md, nextflow.config
After release 2.2.0: bump version to 2.3.0dev
=> bump version to 2.3.0dev

CHANGELOG.md, lib/WorkflowAmpliseq.groovy
Closes https://github.com/nf-core/ampliseq/issues/389
=> error when --qiime_ref_taxonomy and --classifier

CHANGELOG.md, workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/401
=> fix omitting QIIME2_FILTERTAXA

CHANGELOG.md, CITATIONS.md
This is only to correct the release date and to fix the ADONIS citation.
=> update date and adonis citation

CHANGELOG.md, nextflow.config
After release PR to change from version 2.3.1 to 2.4.0dev.
=> bump version to 2.4.0dev

CHANGELOG.md, modules/local/dada2_quality.nf
Closes https://github.com/nf-core/ampliseq/issues/438
_Edit: ok, confirmed the problem myself and also that this is the solution._
=> fix dada2_quality

CHANGELOG.md, nextflow.config
=> Prepare version 2.3.2

CHANGELOG.md, nextflow_schema.json
Closes https://github.com/nf-core/ampliseq/issues/442
I attempted to make the parameter schema more intuitive.
=> update parameter documentation

.github/workflows/ci.yml, CHANGELOG.md, bin/novaseq_err_pe.r, bin/novaseq_err_se.r, conf/modules.config, conf/test_novaseq.config, docs/output.md, docs/usage.md, modules/local/novaseq_err.nf, nextflow.config, nextflow_schema.json, workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/425.
I used https://github.com/nf-core/ampliseq/pull/446 as a template, which can be closed when this PR is merged.
I added test data already: https://github.com/nf-core/test-datasets/pull/592
=> Add NovaSeq data option

docs/output.md
Small update to make the output docs nicer.
=> update output docs

.editorconfig, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, .github/workflows/linting.yml, CHANGELOG.md, CITATION.cff, README.md, assets/email_template.txt, bin/add_full_sequence_to_taxfile.py, bin/add_sh_to_taxonomy.py, bin/count_table_minmax_reads.py, bin/create_unite_taxfile.py, bin/cutadapt_summary.py, bin/filter_stats.py, bin/trunclen.py, conf/base.config, docs/usage.md, lib/WorkflowMain.groovy, main.nf, modules.json, modules/nf-core/modules/custom/dumpsoftwareversions/templates/dumpsoftwareversions.py, nextflow.config, pyproject.toml
This is updating the template from 2.4 to 2.5.1
=> Merging template updates 2.5.1

CHANGELOG.md, nextflow.config
=> bump-version to 2.4.0

CHANGELOG.md, lib/WorkflowAmpliseq.groovy, nextflow.config
After release PR to update pipeline version & fix typo in an error message, reported in https://github.com/nf-core/ampliseq/issues/485
=> Bump version 2.5.0dev

CHANGELOG.md, conf/modules.config, conf/test.config, conf/test_full.config, docs/output.md, modules/local/qiime2_barplot.nf, modules/local/qiime2_featuretable_group.nf, modules/local/qiime2_inasv.nf, nextflow.config, nextflow_schema.json, subworkflows/local/qiime2_barplotavg.nf, workflows/ampliseq.nf
Closes https://github.com/nf-core/ampliseq/issues/393
Check `nf-core linting / nf-core` fails due to the template update 2.6, with 2.5.1 all is fine (tested & linting incl prettier fine). Will attempt the template update later.
=> Add average barplots

CHANGELOG.md, nextflow.config
Version update from 2.5.0dev to 2.4.1 to prepare release
=> change version to 2.4.1

assets/methods_description_template.yml, modules/local/qiime2_alphararefaction.nf, modules/local/qiime2_ancom_asv.nf, modules/local/qiime2_ancom_tax.nf, modules/local/qiime2_barplot.nf, modules/local/qiime2_classify.nf, modules/local/qiime2_diversity_adonis.nf, modules/local/qiime2_diversity_alpha.nf, modules/local/qiime2_diversity_beta.nf, modules/local/qiime2_diversity_betaord.nf, modules/local/qiime2_diversity_core.nf, modules/local/qiime2_export_absolute.nf, modules/local/qiime2_export_relasv.nf, modules/local/qiime2_export_reltax.nf, modules/local/qiime2_extract.nf, modules/local/qiime2_featuretable_group.nf, modules/local/qiime2_filterasv.nf, modules/local/qiime2_filtertaxa.nf, modules/local/qiime2_inasv.nf, modules/local/qiime2_inseq.nf, modules/local/qiime2_intax.nf, modules/local/qiime2_train.nf, modules/local/qiime2_tree.nf, subworkflows/local/dada2_preprocessing.nf, subworkflows/local/qiime2_ancom.nf, subworkflows/local/qiime2_barplotavg.nf, subworkflows/local/qiime2_diversity.nf, workflows/ampliseq.nf
This is to implement review suggestions form https://github.com/nf-core/ampliseq/pull/506
=> Apply review suggestions

modules/local/qiime2_alphararefaction.nf, modules/local/qiime2_ancom_asv.nf, modules/local/qiime2_ancom_tax.nf, modules/local/qiime2_barplot.nf, modules/local/qiime2_classify.nf, modules/local/qiime2_diversity_adonis.nf, modules/local/qiime2_diversity_alpha.nf, modules/local/qiime2_diversity_beta.nf, modules/local/qiime2_diversity_betaord.nf, modules/local/qiime2_diversity_core.nf, modules/local/qiime2_export_absolute.nf, modules/local/qiime2_export_relasv.nf, modules/local/qiime2_export_reltax.nf, modules/local/qiime2_extract.nf, modules/local/qiime2_featuretable_group.nf, modules/local/qiime2_filterasv.nf, modules/local/qiime2_filtertaxa.nf, modules/local/qiime2_inasv.nf, modules/local/qiime2_inseq.nf, modules/local/qiime2_intax.nf, modules/local/qiime2_train.nf, modules/local/qiime2_tree.nf
More cosmetic changes. Mostly double backslashes instead of single backslashes.
=> replace single backslashes with double backslashes

CHANGELOG.md, nextflow.config
Version to 2.5.0dev after release 2.4.1.
=> Bump version to 2.5.0dev

CHANGELOG.md, assets/methods_description_template.yml
Closes https://github.com/nf-core/ampliseq/issues/511
=> Pipeline reference to multiqc report

CHANGELOG.md, modules/local/cutadapt_summary_merge.nf, modules/local/dada2_addspecies.nf, modules/local/dada2_denoising.nf, modules/local/dada2_err.nf, modules/local/dada2_filtntrim.nf, modules/local/dada2_merge.nf, modules/local/dada2_quality.nf, modules/local/dada2_rmchimera.nf, modules/local/dada2_stats.nf, modules/local/dada2_taxonomy.nf, modules/local/merge_stats.nf, modules/local/metadata_all.nf, modules/local/metadata_pairwise.nf, modules/local/novaseq_err.nf
Closes https://github.com/nf-core/ampliseq/issues/512
=> add conda package digest

bin/trunclen.py
Attempt to fix black linting that failed after (not during!) merging https://github.com/nf-core/ampliseq/pull/528
=> fix black formatting

CHANGELOG.md, modules/local/assignsh.nf, modules/local/combine_table.nf, modules/local/cutadapt_summary_merge.nf, modules/local/dada2_addspecies.nf, modules/local/dada2_denoising.nf, modules/local/dada2_err.nf, modules/local/dada2_filtntrim.nf, modules/local/dada2_merge.nf, modules/local/dada2_quality.nf, modules/local/dada2_rmchimera.nf, modules/local/dada2_stats.nf, modules/local/dada2_taxonomy.nf, modules/local/filter_len_asv.nf, modules/local/filter_stats.nf, modules/local/format_taxresults.nf, modules/local/merge_stats.nf, modules/local/metadata_all.nf, modules/local/metadata_pairwise.nf, modules/local/novaseq_err.nf, modules/local/sbdiexport.nf, modules/local/sbdiexportreannotate.nf, modules/local/trunclen.nf
I tested `-profile conda` and added channels where missing.
Solves https://github.com/nf-core/ampliseq/issues/512
=> Fix conda packages

CHANGELOG.md, docs/output.md, docs/usage.md
Updated the metadata documentation in usage (solves https://github.com/nf-core/ampliseq/issues/522) and fixed some links in output description.
=> Update metadata documentation

conf/ref_databases.config, lib/WorkflowAmpliseq.groovy
Add COIdb to sbdi-export compatible databases
=> COI accepted for SBDIexport

CHANGELOG.md, nextflow.config, workflows/ampliseq.nf
Address review suggestions in https://github.com/nf-core/ampliseq/pull/549 by @Emiller88
=> Review suggestions

CHANGELOG.md, nextflow.config
After release update of version number & CHANGELOG
=> Update version to 2.6.0dev

CHANGELOG.md, subworkflows/local/parse_input.nf
Closes https://github.com/nf-core/ampliseq/issues/572
=> fix single end empty file handling

CHANGELOG.md, assets/methods_description_template.yml, nextflow.config
This is just a minimal update of the MultiQC method section. It could be extended to a complete section with all tools and citations. However I am not sure whether I would like to have that rather in the pipeline summary report or in MultiQC. Anyway, taking the shortcut here and modify only whats absolutely required.
=> Update multiqc methods

CHANGELOG.md, conf/modules.config
Closes https://github.com/nf-core/ampliseq/issues/668
=> Prevent masking low complexity regions by VSEARCH

CHANGELOG.md, modules/local/filter_ssu.nf
Fix a broken entry for a conda package.
Closes https://github.com/nf-core/ampliseq/issues/686
=> fix conda package in FILTER_SSU

CHANGELOG.md, CITATIONS.md, docs/usage.md
Documentation needed an update. Especially CITATIONS.md and usage.md missed entries for some taxonomic databases.
=> Update docs, citations and usage with new taxonomic reference databases

CHANGELOG.md, conf/ref_databases.config, nextflow_schema.json
Closes https://github.com/nf-core/ampliseq/issues/780
=> fix --dada_ref_taxonomy silva=132

CHANGELOG.md, conf/ref_databases.config, modules/local/qiime2_alphararefaction.nf, modules/local/qiime2_ancom_asv.nf, modules/local/qiime2_ancom_tax.nf, modules/local/qiime2_ancombc_asv.nf, modules/local/qiime2_ancombc_tax.nf, modules/local/qiime2_barplot.nf, modules/local/qiime2_classify.nf, modules/local/qiime2_diversity_adonis.nf, modules/local/qiime2_diversity_alpha.nf, modules/local/qiime2_diversity_beta.nf, modules/local/qiime2_diversity_betaord.nf, modules/local/qiime2_diversity_core.nf, modules/local/qiime2_export_absolute.nf, modules/local/qiime2_export_relasv.nf, modules/local/qiime2_export_reltax.nf, modules/local/qiime2_extract.nf, modules/local/qiime2_featuretable_group.nf, modules/local/qiime2_filtersamples.nf, modules/local/qiime2_inasv.nf, modules/local/qiime2_inseq.nf, modules/local/qiime2_intax.nf, modules/local/qiime2_intree.nf, modules/local/qiime2_seqfiltertable.nf, modules/local/qiime2_tablefiltertaxa.nf, modules/local/qiime2_train.nf, modules/local/qiime2_tree.nf
This has actually no relevant consequences, as far as I see for now.
=> Update QIIME2 from 2023.7 to 2024.10

.gitignore, CHANGELOG.md, conf/ref_databases.config, nextflow_schema.json, subworkflows/local/utils_nfcore_ampliseq_pipeline/main.nf
I had made a mistake in the pipeline that creates sbdi-gtdb so that sometimes more sequences than specified ended up in output files. I hope this is corrected in the data repo now, and I'm hence adding the new db here.
=> Add new subrelease of sbdi-gtdb: RS220-2

CHANGELOG.md, nextflow_schema.json
Adding a pattern to the input field. Closes https://github.com/nf-core/ampliseq/issues/831.
=> Add pattern to input field

CHANGELOG.md, assets/schema_input.json, assets/schema_multiregion.json, nextflow.config
Closes https://github.com/nf-core/ampliseq/issues/840
=> Fix samplesheet checking

CHANGELOG.md, nextflow_schema.json
Closes https://github.com/nf-core/ampliseq/issues/831
This is _only_ relevant for sequera's Platform afaik.
=> Add pattern to input files

nextflow.config
- [x ] This comment contains a description of changes (with reason).
=> lokesh info as contributor

CHANGELOG.md, conf/ref_databases.config, nextflow_schema.json
Closes https://github.com/nf-core/ampliseq/issues/806
=> Add Greengenes2 version 2024.09 for taxonomic classification with QIIME2

CHANGELOG.md, subworkflows/local/dada2_taxonomy_wf.nf
Closes https://github.com/nf-core/ampliseq/issues/895
=> fix DADA2 with custom database and assignment in chunks
